improvements

diff --git a/dockerComposeServices b/dockerComposeServices
--- a/dockerComposeServices
+++ b/dockerComposeServices
@@ -6,14 +6,15 @@
 #############################################################################
 
 declare yaml=${1:-docker-compose.yml}
-if [ -e "$yaml" ]; then
-
-    declare jsonConfig=$(python -c 'import sys, yaml, json; json.dump(yaml.safe_load(sys.stdin), sys.stdout, indent=4)' < "$yaml" | jq '.services?')
-    if [ "${jsonConfig:-}" ]; then
-        for service in $(jq 'keys[]?' <<< "$jsonConfig"); do
-            eval echo $service
-        done
-    fi
-else
+if [ ! -e "$yaml" ]; then
     echo "Unable to locate $yaml"
+    exit 1
 fi
+
+declare jsonConfig=$(python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' < "$yaml" | jq -c '.services?')
+if [ -z "${jsonConfig:-}" ]; then
+    echo "Invalid file: $yaml"
+    exit 1
+fi
+
+jq -r 'keys[]?' <<< "$jsonConfig"
